local harpoon = require("harpoon")
harpoon:setup()

local keymap = vim.keymap.set
keymap("n", "<leader>a", function()
  harpoon:list():append()
end, { desc = "Append to Harpoon" })
keymap("n", "<C-s>", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Toogle Harpoon Menu" })

keymap("n", "<M-j>", function()
  harpoon:list():select(1)
end, { desc = "Harpoon 1" })
keymap("n", "<M-k>", function()
  harpoon:list():select(2)
end, { desc = "Harpoon 2" })
keymap("n", "<M-l>", function()
  harpoon:list():select(3)
end, { desc = "Harpoon 3" })
keymap("n", "<M-;>", function()
  harpoon:list():select(4)
end, { desc = "Harpoon 4" })

-- Toggle previous & next buffers stored within Harpoon list
keymap("n", "<M-S-k>", function()
  harpoon:list():prev()
end, { desc = "Harpoon Previous" })
keymap("n", "<M-S-j>", function()
  harpoon:list():next()
end, { desc = "Harpoon Next" })
